version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo install docker
      - yum -y update
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      - yum-config-manager --enable docker-ce-nightly
      - yum -y install docker-ce docker-ce-cli containerd.io
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - pwd
      - ls -al
      - docker ps --all
  build:
    commands:
      - echo Build started on `date`
      - chmod 766 gradlew
      - ./gradlew build
      - pwd
      - ls -al
  post_build:
    commands:
      - echo Build completed on `date`
      - pwd
      - ls -al
artifacts:
  files:
    - target/shortz.jar